[package]
name = "absolutechaos"
version = "0.1.0"
edition = "2024"

[dependencies]
rltk = { version = "~0.8", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
specs = { version = "=0.16.1", features = ["serde"] }
specs-derive = "=0.4.1"
